# Generated by Django 4.1.1 on 2024-12-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.TextField(choices=[('Ingenieria Informatica', 'Ingenieria Informatica'), ('Analista Programador', 'Analista Programador'), ('Ingenieria en Ciberseguridad', 'Ingenieria en Ciberseguridad'), ('Tecnico en Telecomunicaciones', 'Tecnico en Telecomunicaciones')], null=True),
        ),
    ]
