# Generated by Django 4.1.1 on 2024-12-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.TextField(choices=[('IEI', 'IEI'), ('AP', 'AP')], null=True),
        ),
    ]
