# Generated by Django 4.1.1 on 2024-12-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_voted_main_account_voted_iei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.TextField(choices=[('AP', 'AP')], null=True),
        ),
    ]
