# Generated by Django 4.1.1 on 2024-12-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='voted_iei',
        ),
        migrations.AddField(
            model_name='account',
            name='private_key',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
