# Generated by Django 4.1.1 on 2024-12-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_voted_iei_account_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
