# Generated by Django 4.1.1 on 2024-12-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
