# Generated by Django 4.1.1 on 2024-12-12 03:46

from django.conf import settings
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_iei_candidate_remove_ceit_candidate_voters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingschedule',
            name='department',
            field=models.TextField(choices=[('IEI', 'IEI'), ('AP', 'AP')], null=True),
        ),
        migrations.CreateModel(
            name='AP_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(default=main.models.modalID_generator, editable=False, max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='candidates')),
                ('bio', models.TextField(null=True)),
                ('position', models.TextField(choices=[('Delegado Estudiantil', 'Delegado Estudiantil')], null=True)),
                ('voters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
