# Generated by Django 4.1.1 on 2024-12-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_delegado_estudiantil_receipt_delegado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_candidate',
            name='position',
            field=models.TextField(choices=[('Delegado_Estudiantil', 'Delegado Estudiantil')], null=True),
        ),
    ]
