# Generated by Django 4.1.1 on 2024-12-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_votingschedule_department_delete_iei_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='delegado_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='qr_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
